language: python

python:
    - "3.5"

env:
    global:
        - TEST_DIR=/tmp/module_testing
        - MODULE=ielearn

install:
    source .travis/install.sh

script:
    bash .travis/test.sh

after_success:
    source .travis/after_success.sh

notifications:
    email:
        recipients:
            - anthonyagnone@gmail.com
        on_success: never
        on_failure: always
